GET http://localhost:8080/
###
GET http://localhost:8080/recipe/4

###
GET http://localhost:8080/info
###
POST http://localhost:8080/recipe
Content-Type: application/json

{
  "Title": "каша",
  "cookingTime": "30",
  "ingredients": [
    {
      "title": "гречка",
      "number": 300,
      "measure": "г"
    }
    ],
  "steps": [
    "Step 1",
    "Step 2",
    "Step 3"
  ]

      }
###
GET http://localhost:8080/recipe
###
GET http://localhost:8080/recipe/0
###
DELETE http://localhost:8080/recipe/0

###
GET http://localhost:8080/ingredient
###
GET http://localhost:8080/ingredient/14
###
POST http://localhost:8080/ingredient
Content-Type: application/json


{
"title": "макароны",
"number": 100,
"measure": "мл"
}

###
DELETE http://localhost:8080/ingredient/5


